--Order_Events validation query
--SELECT 
--SELECT EVENT_TYPE, COUNT(*)
--FROM ORDER_EVENTS
--GROUP BY EVENT_TYPE;


--User name validation query
--SELECT EMAIL, USERNAME 
--FROM HEVO_ASSESSMENT_1_CUSTOMERS 
--LIMIT 10;

--SELECT COUNT(*) FROM HEVO_ASSESSMENT_1_CUSTOMERS;
--SELECT COUNT(*) FROM ORDER_EVENTS;
